// <auto-generated />
namespace Dosermana.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderItem_new_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderItem_new_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202404120601051_OrderItem_new_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
